### PR TITLE
feat: add rupture-no-conflict

### LINKED ISSUE #76: no-conflict mode
Would a PR adding a no-conflict mode be accepted?

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
closes #76

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@jescalan I've reached the limit of my stylus-foo with this one.

Moving the non-prefixed name outside of the function declaration meant that the function body has issue's with name classes, specifically when declaring media orientation.

I was able to tackle most by using the `s()` function. But there seems to be a problem when conditions are built using strings and then passed to the `@media` mixin.

You can check out the `conditions` string before this line
https://github.com/BerkeleyTrue/rupture/blob/9430e10daabc57534bf64b4b7783a7493c4df208/rupture/index.styl#L145

It will look right, but the output will replace `landscape` with `rupture-landscape`.

It seems that this issue also arises when using the no conflict mode, but I'm also not sure why.
I'm not sure how to prevent the `@media` tag from interpreting the contents of a string. Any advice would be much appreciated. 

What I had hoped would only take me a couple of minutes ended up with me diving down deep into stylus.

**Comment by BerkeleyTrue** [comment]
I've made a [codepen](https://codepen.io/BerkeleyTrue/pen/amPQER) demonstrating the issue.

**Comment by jescalan** [comment]
Hey @BerkeleyTrue -- I'm sorry but I'm not entirely how to solve this one off the top 😭 Maybe @declandewet might be able to help?

**Comment by declandewet** [comment]
Sorry for the late response - if I recall, I did a lot of digging into this around the time I was implementing #54 and I ran into a very similar issue, and couldn't find any problems with the code itself - based on docs at the time, the code in that PR should have worked, but didn't. I ~~deduced~~ assumed it was a bug in Stylus. I remember doing a small experiment to see if implementing no-conflict using the JS api would be easier, and it was - but would be a lot of work to get Rupture's codebase to adapt to that strategy - not something I was particularly excited about with the prospect of PostCSS looming closer.

**Comment by BerkeleyTrue** [comment]
@declandewet Thanks for your response. 

I've did some digging through SO, but found nothing satisfactory. I've posted a question myself. 
http://stackoverflow.com/questions/40270672/stylus-prevent-media-tag-from-interpreting-strings

**Comment by BerkeleyTrue** [comment]
@jescalan I've found a solution thanks to SO using, ironically, interpolation.

```styl
landscape = 'not-landscape';
condition = "screen and (orientation: landscape)";
@media ({condition})
   color: red
```
results in:

```css
@media (only screen and (orientation: landscape)) {
  color: red;
}
```

This adds an extra wrapping parenthesis around media tags generated by rupture. I dislike this but it is the only way I have found to get no-conflict mode working correctly.

Please let me know your thoughts.

**Comment by jescalan** [comment]
Seems ok to me! That being said, I don't use stylus anymore, nor have I ever had a use for no conflict mode, so it's possible that others' opinions won't line up. If anyone else is watching this and objected, speak up now!

**Comment by BerkeleyTrue** [comment]
@jescalan So what's the word?

**Comment by jescalan** [comment]
I guess it passes!

**Comment by jescalan** [comment]
And of course, thank you so much for your hard work and this awesome contribution 😁 🎉

**Pull request merged**
